source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView


app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset')
]

source/api/urls.py
from django.urls import path


app_name = 'api'


urlpatterns = [

]

source/main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views.views import IndexView, FriendChoseView, FriendDelView

app_name = 'webapp'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('friend/<int:pk>/like/', FriendChoseView.as_view(), name='friend_chose'),
    path('friend/<int:pk>/unlike/', FriendDelView.as_view(), name='friend_del'),

]

source/webapp/models.py
from django.db import models

# Create your models here.

source/webapp/forms.py
from django import forms


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")

source/webapp/views/base_view.py
from django.db.models import Q
from django.views.generic import ListView as DjangoListView

from webapp.forms import SimpleSearchForm


class SearchView(DjangoListView):
    search_form_class = SimpleSearchForm
    search_form_field = 'search'
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value(self.search_form)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = self.search_form
        context['search_value'] = self.search_value
        return context

    def get_queryset(self):
        data = super(SearchView, self).get_queryset()
        query = self.get_query(self.search_value)
        data = data.filter(query)
        return data

    def get_search_form(self):
        return self.search_form_class(data=self.request.GET)

    def get_search_value(self, form):
        search_value = None
        if form.is_valid():
            search_value = form.cleaned_data.get(self.search_form_field, None)
        return search_value

    def get_query(self, search_value):
        query = Q()
        if search_value:
            for field in self.search_fields:
                kwargs = {field: search_value}
                query = query | Q(**kwargs)
        return query

source/webapp/views/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseForbidden
# from django.shortcuts import render
from django.views.generic.base import View
# from rest_framework.authtoken.admin import User
from rest_framework.generics import get_object_or_404

from webapp.views.base_view import SearchView
from accounts.models import Profile, FriendList


class IndexView(SearchView):
    template_name = 'index.html'
    context_object_name = 'profiles'
    paginate_by = 2
    paginate_orphans = 0
    model = get_user_model()
    # ordering = ['-created_at']
    search_fields = ['first_name__icontains', 'last_name__icontains']


class FriendChoseView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        chosen_friend = get_object_or_404(Profile, pk=kwargs.get('pk'))
        like, created = FriendList.objects.get_or_create(profile=chosen_friend, user=request.user)
        if created:
            chosen_friend.save()
            return HttpResponse()
        else:
            return HttpResponseForbidden()


class FriendDelView(LoginRequiredMixin, View):
    def delete(self, request, *args, **kwargs):
        friend = get_object_or_404(Profile, pk=kwargs.get('pk'))
        like = get_object_or_404(friend.friends, user=request.user)
        like.delete()
        friend.save()
        return HttpResponse()


class FriendListView(LoginRequiredMixin, View):
    template_name = 'user_detail.html'
    context_object_name = 'friends'
    paginate_by = 3
    paginate_orphans = 0
    model = FriendList

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}My Site{% endblock %}</title>

    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block links %}{% endblock %}
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <ul class="menu">
                <li><a href="{% url "webapp:index" %}">Home</a></li>
{#                <li><a href="{% url "webapp:cart_view" %}">Cart</a></li>#}
                {% if request.user.is_authenticated %}
{#                    <li><a href="{% url "webapp:product_create" %}">Add Product</a></li>#}
                    {% block menu %}{% endblock %}
                    <li><a href="{% url 'accounts:detail' request.user.pk %}">
                        Привет, {{ request.user.get_full_name|default:request.user.username }}
                    </a></li>
                {% endif %}
                {% block auth_menu %}
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Login</a></li>
                        <li><a href="{% url 'accounts:create' %}?next={{ request.get_full_path }}">Sign Up</a></li>
                    {% endif %}
                {% endblock %}
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:password_reset_email' %}">Reset Password</a></li>
                {% endif %}
            </ul>

            {% block search %}
                {% if search_form %}
                    <div class="search-form">
                        <form action="{% url 'webapp:index' %}" method="GET">
                            {{ search_form.search }}
                            <input type="submit" value="Найти">
                        </form>
                    </div>
                {% endif %}
            {% endblock %}
        </div>
    </nav>
    <div class="container">
        {% include 'partial/messages.html' %}
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/index.html
{% extends 'base.html' %}

{% block title %}Chat{% endblock %}

{% block content %}
    <h1>Welcome!</h1>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}

    {% for user_obj in profiles %}
         <div class="box">
{#            <h3><a href="{% url 'webapp:photo_view' photo.pk %}">{{ photo.text }}</a></h3>#}
            {% if user_obj.profile.avatar %}
                <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="50" height="50" alt="photo">
            {% endif %}
            <p>Имя: {{ user_obj.first_name }}</p>
            <p>Фамилия: {{ user_obj.last_name }}</p>
             <p><a href="{% url 'accounts:detail' user_obj.pk %}">{{ user_obj.username }}</a></p>

            {% if perms.webapp.change_product or product.author == request.user %}
{#                <p><a href="{% url 'accounts:photo_delete' photo.pk %}">Delete</a></p>#}
{#                <p><a href="{% url 'webapp:photo_update' photo.pk %}">Update</a></p>#}
            {% endif %}
          <p>
            <a class="{% if like in chosen_friend %}hidden{% endif %} like" href="{% url 'webapp:friend_chose' user_obj.pk %}">Добавить в друзья</a>
            <a class="{% if not like in chosen_friend %}hidden{% endif %} unlike" href="{% url 'webapp:friend_del' user_obj.pk %}">Убрать из друзей</a>
          </p>
         </div>
    {% endfor %}
{% endblock %}